%% wxrecordvideo
 % Record video using the camera Logitech (USB Video Device)
 % JL Alatorre-Warren

%% Initial setup

% Get relevant information from wxtmaze
[pathRoot,...
 pathData,...
 pathRois,...
 pathTrials,...
 pathTrialList,...
 structureOfTrials,...
 listOfedTrials,...
 trialName,...
 pathCurrentTrial,...
 mouseName,...
 experimentName,...
 timestampVector,...
 dateString,...
 timeString] = wxlistentowxtmaze; %#ok<*ASGLU>

% Get the rest of the information
[~,...
 ~,...
 ~,...
 ~,...
 ~,...
 ~,...
 pathMouseName,...
 pathDateString,...
 pathExperimentName,...
 pathTimeString,...
 pathFlags,...
 pathSignals,...
 pathFrames] = wxcreatedirectories(timestampVector,... 
                                   mouseName,...
                                   dateString,...
                                   experimentName,...
                                   timeString);
                                  
% Send flag to wxtmaze
flagRecordVideoReady = true; %#ok<*NASGU>
save([pathFlags '/' 'flagrecordvideoready.mat'], 'flagRecordVideoReady');

%% Setup live preview

% Create axes control
handleToAxes = axes();

% Get the handle to the image
hImage = image(zeros(480,640,'uint8'));
hold off;
axis auto;
axis on;

% Set the property OuterPosition of the figure
set(gcf, 'Units', 'Pixels', 'OuterPosition', [1281 741 869 700]);

% Preview webcam Logitech
listOfWebcams = webcamlist;
cameraObject = webcam(listOfWebcams{1,1});
preview(cameraObject, hImage);

%% Record video

% Track time
tic

% Save frames until flag sent from wxtmaze is found
flagFound = false;
while flagFound == false
  
  % Take snapshot
  currentFrame = snapshot(cameraObject); 
         
  % Save the data that is currently available
  save([pathFrames     '/' ...
        'frame'        '_' ...
        mouseName      '_' ...
        experimentName '_' ...
        datestr(now,'yyyymmddHHMMSSFFF') '.mat'], ...
        'currentFrame');
      
  % Search flag and break the loop if found
  flagSequenceCompleted = exist([pathFlags '/' 'flagsequencecompleted.mat'],'file');  
  if (flagSequenceCompleted == 2)
    flagFound = true;
  end
         
  toc
end
clear currentFrame

% Produce video once the T-maze has been completed (flag has been found)
wxproducevideo(pathFrames)

% Close MATLAB session
exit